GET http://localhost:5000

###
GET http://localhost:5000/api/logger

###
POST http://localhost:5000/api/mentorship
Content-Type: application/json

{
    "fullName": "david kraku",
    "email": "davidkraku69@gmail.com",
    "phone": "234232432324322"
}