const github = (slug) => `https://github.com/kofiarhin/${slug}`;
const og = (slug) => `https://opengraph.githubassets.com/1/kofiarhin/${slug}`;

export const workPortfolio = [
  {
    key: "hibachi",
    aliases: ["hibachi"],
    name: "Hibachi",
    description: "Local-first, voice-first personal operating agent for governed software delivery, controlled tool execution, approvals, verification, and accessible operation.",
    features: ["Governed AI agent execution", "Approval-gated software delivery", "Typed tools and verification"],
    status: "Active",
    category: "AI Agent Engineering",
    featured: true,
    displayOrder: 1,
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788069502/devkofi/projects/hibachi-thumbnail.webp",
    repoUrl: null,
  },
  {
    key: "context-api",
    aliases: ["context api", "context-api"],
    name: "Context API",
    description: "Structured context and engineering control-plane API for agents, project memory, GitHub workflows, and governed provider operations.",
    features: ["Structured context retrieval", "Governed GitHub and provider gateways", "Machine-readable engineering context"],
    status: "Active",
    category: "AI Infrastructure",
    featured: true,
    displayOrder: 2,
    repoUrl: github("context-api"),
    demoUrl: "https://context-api-3b9dfadf403e.herokuapp.com",
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788069264/devkofi/projects/context-api-thumbnail.webp",
  },
  {
    key: "brain",
    aliases: ["brain"],
    name: "Brain",
    description: "Full-stack personal operating system combining durable MongoDB memory, AI-assisted workflows, retrieval, and a responsive product interface.",
    features: ["MongoDB-backed durable memory", "AI-assisted workflows", "Context-aware retrieval and chat"],
    status: "Active",
    category: "AI Product Engineering",
    featured: true,
    displayOrder: 3,
    repoUrl: github("brain"),
    demoUrl: "https://brain-pi-black.vercel.app",
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1787967827/c4eiah6tqqf1njxs7wj8.png",
  },
  {
    key: "leadradar",
    aliases: ["leadradar", "lead radar"],
    name: "LeadRadar",
    description: "B2B prospecting system that turns public LinkedIn engagement into qualified prospects, verified business contacts, governed outreach, and sales opportunities.",
    features: ["Prospect qualification", "Contact enrichment", "Human-approved outreach orchestration"],
    status: "In development",
    category: "AI Product Engineering",
    displayOrder: 4,
    repoUrl: github("leadradar"),
    thumbnailUrl: og("leadradar"),
  },
  {
    key: "forge",
    aliases: ["forge"],
    name: "Forge",
    description: "AI-powered software organization for coordinating specialist agents through governed implementation, verification, and release preparation.",
    features: ["Agent orchestration", "Approval-gated execution", "Evidence-backed workflow state"],
    status: "In development",
    category: "Agent Orchestration",
    displayOrder: 5,
    repoUrl: github("forge"),
    thumbnailUrl: og("forge"),
  },
  {
    key: "thriftchef",
    aliases: ["thriftchef", "thrift chef"],
    name: "ThriftChef",
    description: "Retailer-aware budget meal planner that generates practical meal plans and consolidated shopping lists against a hard household budget.",
    features: ["Deterministic planning engine", "Retailer-aware pricing", "Production full-stack product"],
    status: "Active",
    category: "Product Engineering",
    displayOrder: 6,
    repoUrl: github("thriftchef"),
    demoUrl: "https://thriftchef.vercel.app",
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1787967836/vxxoyiakgw6o1xeow6yw.png",
  },
];

export const engineeringSystemsPortfolio = [
  {
    key: "ai-dev-workspace",
    aliases: ["ai dev workspace", "ai-dev-workspace"],
    name: "AI Dev Workspace",
    description: "Repository-local AI software-delivery operating system with project memory, health auditing, governed ticket delivery, TDD, verification, and safe publication boundaries.",
    features: ["11-skill delivery system", "Project truth and health auditing", "TDD and publication gates"],
    status: "Active",
    category: "Engineering Operating System",
    displayOrder: 1,
    repoUrl: github("ai-dev-workspace"),
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788069577/devkofi/projects/ai-dev-workspace-thumbnail.webp",
  },
  {
    key: "codex-workflow-kit",
    aliases: ["codex workflow kit", "codex workflow", "codex-workflow-kit"],
    name: "Codex Workflow Kit",
    description: "Reusable AI engineering workflow that turns plain-language requests into clarified, approved, run-scoped implementation with memory, TDD, review, verification, and handoff.",
    features: ["Structured intake and approval", "Run-scoped project memory", "TDD, review, and verification"],
    status: "Active",
    category: "Engineering Workflow",
    displayOrder: 2,
    repoUrl: github("codex-workflow-kit"),
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788069442/devkofi/projects/codex-workflow-kit-thumbnail.webp",
  },
  {
    key: "agent-system",
    aliases: ["agent system", "universal agent system", "agent-system"],
    name: "Agent System",
    description: "Runtime-agnostic instruction infrastructure that compiles shared agent behaviour into verified native instructions for Codex, Claude Code, Gemini CLI, and other runtimes.",
    features: ["Shared instruction source of truth", "Runtime adapters", "Deterministic build and verification"],
    status: "Active",
    category: "Agent Infrastructure",
    displayOrder: 3,
    repoUrl: github("agent-system"),
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788130712/devkofi/agent-system-cover-20260831.png",
  },
  {
    key: "context-api",
    aliases: ["context api", "context-api"],
    name: "Context API",
    description: "Structured machine context and governed engineering control plane used to give agents compact project knowledge and bounded operational capabilities.",
    features: ["Bounded context resolution", "Structured project memory", "Governed operational gateways"],
    status: "Active",
    category: "Context Infrastructure",
    displayOrder: 4,
    repoUrl: github("context-api"),
    demoUrl: "https://context-api-3b9dfadf403e.herokuapp.com",
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788069264/devkofi/projects/context-api-thumbnail.webp",
  },
  {
    key: "ideahub",
    aliases: ["ideas hub", "ideahub", "ideas"],
    name: "Ideas Hub",
    description: "Markdown-first durable project knowledge system with deterministic catalogues, shared awareness, governed synchronization, and MCP tooling.",
    features: ["Durable project knowledge", "Deterministic retrieval indexes", "Shared awareness and MCP tooling"],
    status: "Active",
    category: "Knowledge Infrastructure",
    displayOrder: 5,
    repoUrl: github("ideahub"),
    thumbnailUrl: "https://res.cloudinary.com/dlsiabgiw/image/upload/v1788131343/devkofi/projects/ideahub-knowledge-thumbnail-20260830.png",
  },
];
