export const services = [
  {
    id: "ai-systems-engineering",
    title: "AI Systems Engineering",
    eyebrow: "Flagship service",
    problem: "You have a promising AI idea or prototype, but it still needs the surrounding software, controls, integrations, and verification to become dependable.",
    description: "I design and engineer production-oriented AI systems around your real software, data, workflows, and users.",
    useCases: ["Tool-using AI agents", "Human-in-the-loop workflows", "Context and memory systems", "Evaluation and verification layers"],
  },
  {
    id: "ai-product-engineering",
    title: "AI Product Engineering",
    eyebrow: "Product development",
    problem: "You need AI to be part of the product experience, not a disconnected experiment.",
    description: "I build AI-native products and substantial AI features across frontend, backend, data, model integrations, and product UX.",
    useCases: ["AI SaaS products", "Copilots", "Internal AI applications", "AI developer tools"],
  },
  {
    id: "agentic-workflows",
    title: "Agentic Workflow Engineering",
    eyebrow: "Complex workflows",
    problem: "Your workflow needs reasoning, state, tools, validation, approvals, or recovery that simple trigger-action automation cannot provide.",
    description: "I engineer governed multi-step workflows where agents interact with software, data, and people safely and predictably.",
    useCases: ["Research and operations agents", "Approval-driven workflows", "Multi-step tool orchestration", "Validation and remediation loops"],
  },
  {
    id: "ai-integration",
    title: "AI Integration",
    eyebrow: "Existing software",
    problem: "You already have a product or internal system and need AI introduced without destabilising the rest of the stack.",
    description: "I integrate LLMs, AI APIs, tool use, retrieval, and model-driven features into existing applications with clear boundaries.",
    useCases: ["LLM integrations", "AI APIs", "Existing product features", "Internal software integrations"],
  },
  {
    id: "context-knowledge",
    title: "AI Context & Knowledge Systems",
    eyebrow: "Retrieval and memory",
    problem: "Your AI system is only as useful as the context it can reliably retrieve, structure, and apply.",
    description: "I build retrieval, memory, and context infrastructure for AI applications that need grounded, reusable knowledge.",
    useCases: ["RAG", "Semantic retrieval", "Agent memory", "Context APIs"],
  },
  {
    id: "engineering-partner",
    title: "AI Engineering Partner",
    eyebrow: "Ongoing support",
    problem: "Your AI system is live or evolving and needs senior engineering attention as requirements and model behaviour change.",
    description: "I provide ongoing engineering support for reliability, integrations, evaluations, architecture, and capability expansion.",
    useCases: ["Reliability improvements", "New integrations", "Evaluation systems", "Architecture evolution"],
  },
];
