export const pricingPlans = [
  {
    id: "standard",
    title: "Full-Stack Bootcamp: Standard",
    price: "£1,200",
    frequency: "one-time",
    description: "Perfect for self-starters who want structure and community.",
    features: [
      "6-month full-stack web development bootcamp",
      "Weekly live sessions & lifetime recordings",
      "10+ real-world portfolio projects",
      "Private student community",
      "End-of-course certificate",
      "14-day refund guarantee",
    ],
    ctaText: "Join Standard",
    ctaLink: "/contact",
    isPopular: false,
  },
  {
    id: "pro",
    title: "Full-Stack Bootcamp: Pro",
    price: "£1,800",
    frequency: "one-time",
    description:
      "For those who want hands-on accountability and faster growth.",
    features: [
      "All Standard features included",
      "Bi-weekly 1:1 mentorship sessions",
      "Detailed code reviews & feedback",
      "Personalized portfolio & career guidance",
      "Priority Slack/Discord support",
      "14-day refund guarantee",
    ],
    ctaText: "Go Pro",
    ctaLink: "/contact",
    isPopular: true, // Highlights this card
  },
  {
    id: "team",
    title: "Team / Enterprise",
    price: "£5,000",
    frequency: "up to 5 members",
    description: "Upskill your small team with dedicated support.",
    features: [
      "Team access & custom scheduling",
      "Team-focused real-world projects",
      "Dedicated instructor support",
      "Post-course team audit & recommendations",
      "Private Slack channel for your team",
      "14-day refund guarantee",
    ],
    ctaText: "Request Access",
    ctaLink: "/contact",
    isPopular: false,
  },
];
