import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAdminMessages, useMessageMutation } from '../../hooks/useAdminData';
import s from './Admin.module.scss';

const AdminMessages = () => {
  const [filters, setFilters] = useState({ page: 1, limit: 20, search: '', read: 'all', archived: 'false' });
  const { data, isLoading, isError } = useAdminMessages(filters); const mutation = useMessageMutation();
  const result = data?.data?.data || {};
  const run = (message, action, isRead) => { if ((action === 'archive' || action === 'restore') && !window.confirm(`${action === 'archive' ? 'Archive' : 'Restore'} message from ${message.name}?`)) return; mutation.mutate({ id: message._id, action, isRead }); };
  return <section className={s.page}><header className={s.header}><div><h1>Messages</h1><p>Review and triage contact enquiries.</p></div></header><div className={s.toolbar}><input className={s.input} aria-label="Search messages" placeholder="Search messages" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value, page: 1 })}/><select className={s.select} aria-label="Read state" value={filters.read} onChange={(e) => setFilters({ ...filters, read: e.target.value, page: 1 })}><option value="all">All</option><option value="unread">Unread</option><option value="read">Read</option></select><select className={s.select} aria-label="Archive state" value={filters.archived} onChange={(e) => setFilters({ ...filters, archived: e.target.value, page: 1 })}><option value="false">Inbox</option><option value="true">Archived</option><option value="all">All records</option></select></div>{isLoading ? <p>Loading messages…</p> : isError ? <p className={s.error}>Could not load messages.</p> : !result.items?.length ? <p className={s.card}>No messages match these filters.</p> : <div className={s.tableWrap}><table className={s.table}><thead><tr><th>From</th><th>Subject</th><th>State</th><th>Date</th><th>Actions</th></tr></thead><tbody>{result.items.map((message) => <tr key={message._id}><td><strong>{message.name}</strong><div className={s.muted}>{message.email}</div></td><td>{message.subject}</td><td><span className={s.status}>{message.isArchived ? 'archived' : message.isRead ? 'read' : 'unread'}</span></td><td>{new Date(message.createdAt).toLocaleDateString()}</td><td><div className={s.actions}><Link className={s.button} to={`/admin/messages/${message._id}`}>View</Link><button className={s.button} onClick={() => run(message, 'read-state', !message.isRead)}>Mark {message.isRead ? 'unread' : 'read'}</button>{message.isArchived ? <button className={s.button} onClick={() => run(message, 'restore')}>Restore</button> : <button className={s.danger} onClick={() => run(message, 'archive')}>Archive</button>}</div></td></tr>)}</tbody></table></div>}</section>;
};
export default AdminMessages;
