name: Deploy client to Namecheap

on:
  push:
    branches: [ main ]  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install & build (client)
        working-directory: client
        run: |
          npm ci
          npm run build   # outputs to client/dist

      - name: Upload dist contents to public_html
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ${{ secrets.FTP_PROTOCOL }}  # ftps
          local-dir: client/dist/   # uploads the CONTENTS of dist
          server-dir: /             # / == public_html for your FTP user
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
