name: Deploy client to root public_html

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install & build (client)
        working-directory: client
        run: |
          npm ci
          npm run build   # -> client/dist

      - name: Upload dist contents to *root* public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}       # e.g. server345.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}   # deploy@devkofi.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}           # 21
          protocol: ${{ secrets.FTP_PROTOCOL }}   # ftps
          local-dir: client/dist/                 # upload CONTENTS of dist
          server-dir: /../public_html/            # go up one level, then into root public_html
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
