name: Deploy client to Namecheap

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install & build (client)
        working-directory: client
        run: |
          npm ci
          npm run build   # -> client/dist

      - name: Verify build output exists
        run: |
          test -d client/dist && echo "dist exists ✅" || (echo "dist missing ❌" && exit 1)

      - name: Upload dist contents to public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}       # e.g. server345.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}   # deploy@devkofi.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}           # 21
          protocol: ${{ secrets.FTP_PROTOCOL }}   # ftps
          local-dir: client/dist/                 # uploads CONTENTS of dist
          server-dir: /public_html/               # explicit web root
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
